#!/bin/bash

# if [[ -z $VIRTUAL_ENV ]]; then
#   echo "You're not in a virtualenv, do you really want to go on?"
#   read confirmation
#   if [[ $confirmation != "y" && $confirmation != "Y" ]]; then
#     exit 1;
#   fi
# fi

# pip $*